[book]
authors = ["La IslaBTC"]
language = "es"
multilingual = false
src = "src"
title = "Proyecto de desarrollo local"

[output.html]
git-repository-url = "https://github.com/Delgado74/proyecto"
edit-url-template = ""


